# Tasks for device 1

# "Erasing KellyMcKernan"
# CUDA_VISIBLE_DEVICES=1 python train_adversarial_gumbel_v7.py                     --save_freq 100                     --models_path=models                     --prompt "KellyMcKernan"                     --seperator ","                     --train_method "xattn"                     --config_path "configs/stable-diffusion/v1-inference.yaml"                     --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt"                     --diffusers_config_path "../Better_Erasing/models/erase/config.json"                     --vocab "artistic"                     --info "gumbel_v7_lr_1e-2_temp_2_hard_0_topk_5_num_100_update_-1_timestep_0_multi_2_kclosest_1000_artistic"                     
CUDA_VISIBLE_DEVICES=1 python eval-scripts/generate-images.py                     --models_path=models                     --model_name="compvis-adversarial-gumbel-word_KellyMcKernan-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_gumbel_v7_lr_1e-2_temp_2_hard_0_topk_5_num_100_update_-1_timestep_0_multi_2_kclosest_1000_artistic"                     --prompts_path "data/short_niche_art_prompts.csv"                     --save_path "evaluation_folder"                     --num_samples 1                     
CUDA_VISIBLE_DEVICES=1 python eval-scripts/generate-images.py                     --models_path=models                     --model_name="compvis-adversarial-gumbel-word_KellyMcKernan-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_gumbel_v7_lr_1e-2_temp_2_hard_0_topk_5_num_100_update_-1_timestep_0_multi_2_kclosest_1000_artistic"                     --prompts_path "data/long_niche_art_prompts.csv"                     --save_path "evaluation_massive"                     --num_samples 5                     
# "Erasing ThomasKinkade"
CUDA_VISIBLE_DEVICES=1 python train_adversarial_gumbel_v7.py                     --save_freq 100                     --models_path=models                     --prompt "ThomasKinkade"                     --seperator ","                     --train_method "xattn"                     --config_path "configs/stable-diffusion/v1-inference.yaml"                     --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt"                     --diffusers_config_path "../Better_Erasing/models/erase/config.json"                     --vocab "artistic"                     --info "gumbel_v7_lr_1e-2_temp_2_hard_0_topk_5_num_100_update_-1_timestep_0_multi_2_kclosest_1000_artistic"                     
CUDA_VISIBLE_DEVICES=1 python eval-scripts/generate-images.py                     --models_path=models                     --model_name="compvis-adversarial-gumbel-word_ThomasKinkade-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_gumbel_v7_lr_1e-2_temp_2_hard_0_topk_5_num_100_update_-1_timestep_0_multi_2_kclosest_1000_artistic"                     --prompts_path "data/short_niche_art_prompts.csv"                     --save_path "evaluation_folder"                     --num_samples 1                     
CUDA_VISIBLE_DEVICES=1 python eval-scripts/generate-images.py                     --models_path=models                     --model_name="compvis-adversarial-gumbel-word_ThomasKinkade-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_gumbel_v7_lr_1e-2_temp_2_hard_0_topk_5_num_100_update_-1_timestep_0_multi_2_kclosest_1000_artistic"                     --prompts_path "data/long_niche_art_prompts.csv"                     --save_path "evaluation_massive"                     --num_samples 5                     
# "Erasing AjinDemiHuman"
CUDA_VISIBLE_DEVICES=1 python train_adversarial_gumbel_v7.py                     --save_freq 100                     --models_path=models                     --prompt "AjinDemiHuman"                     --seperator ","                     --train_method "xattn"                     --config_path "configs/stable-diffusion/v1-inference.yaml"                     --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt"                     --diffusers_config_path "../Better_Erasing/models/erase/config.json"                     --vocab "artistic"                     --info "gumbel_v7_lr_1e-2_temp_2_hard_0_topk_5_num_100_update_-1_timestep_0_multi_2_kclosest_1000_artistic"                     
CUDA_VISIBLE_DEVICES=1 python eval-scripts/generate-images.py                     --models_path=models                     --model_name="compvis-adversarial-gumbel-word_AjinDemiHuman-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_gumbel_v7_lr_1e-2_temp_2_hard_0_topk_5_num_100_update_-1_timestep_0_multi_2_kclosest_1000_artistic"                     --prompts_path "data/short_niche_art_prompts.csv"                     --save_path "evaluation_folder"                     --num_samples 1                     
CUDA_VISIBLE_DEVICES=1 python eval-scripts/generate-images.py                     --models_path=models                     --model_name="compvis-adversarial-gumbel-word_AjinDemiHuman-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_gumbel_v7_lr_1e-2_temp_2_hard_0_topk_5_num_100_update_-1_timestep_0_multi_2_kclosest_1000_artistic"                     --prompts_path "data/long_niche_art_prompts.csv"                     --save_path "evaluation_massive"                     --num_samples 5                     
# "Erasing TylerEdlin"
CUDA_VISIBLE_DEVICES=1 python train_adversarial_gumbel_v7.py                     --save_freq 100                     --models_path=models                     --prompt "TylerEdlin"                     --seperator ","                     --train_method "xattn"                     --config_path "configs/stable-diffusion/v1-inference.yaml"                     --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt"                     --diffusers_config_path "../Better_Erasing/models/erase/config.json"                     --vocab "artistic"                     --info "gumbel_v7_lr_1e-2_temp_2_hard_0_topk_5_num_100_update_-1_timestep_0_multi_2_kclosest_1000_artistic"                     
CUDA_VISIBLE_DEVICES=1 python eval-scripts/generate-images.py                     --models_path=models                     --model_name="compvis-adversarial-gumbel-word_TylerEdlin-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_gumbel_v7_lr_1e-2_temp_2_hard_0_topk_5_num_100_update_-1_timestep_0_multi_2_kclosest_1000_artistic"                     --prompts_path "data/short_niche_art_prompts.csv"                     --save_path "evaluation_folder"                     --num_samples 1                     
CUDA_VISIBLE_DEVICES=1 python eval-scripts/generate-images.py                     --models_path=models                     --model_name="compvis-adversarial-gumbel-word_TylerEdlin-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_gumbel_v7_lr_1e-2_temp_2_hard_0_topk_5_num_100_update_-1_timestep_0_multi_2_kclosest_1000_artistic"                     --prompts_path "data/long_niche_art_prompts.csv"                     --save_path "evaluation_massive"                     --num_samples 5                     
# "Erasing KilianEng"
CUDA_VISIBLE_DEVICES=1 python train_adversarial_gumbel_v7.py                     --save_freq 100                     --models_path=models                     --prompt "KilianEng"                     --seperator ","                     --train_method "xattn"                     --config_path "configs/stable-diffusion/v1-inference.yaml"                     --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt"                     --diffusers_config_path "../Better_Erasing/models/erase/config.json"                     --vocab "artistic"                     --info "gumbel_v7_lr_1e-2_temp_2_hard_0_topk_5_num_100_update_-1_timestep_0_multi_2_kclosest_1000_artistic"                     
CUDA_VISIBLE_DEVICES=1 python eval-scripts/generate-images.py                     --models_path=models                     --model_name="compvis-adversarial-gumbel-word_KilianEng-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_gumbel_v7_lr_1e-2_temp_2_hard_0_topk_5_num_100_update_-1_timestep_0_multi_2_kclosest_1000_artistic"                     --prompts_path "data/short_niche_art_prompts.csv"                     --save_path "evaluation_folder"                     --num_samples 1                     
CUDA_VISIBLE_DEVICES=1 python eval-scripts/generate-images.py                     --models_path=models                     --model_name="compvis-adversarial-gumbel-word_KilianEng-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_gumbel_v7_lr_1e-2_temp_2_hard_0_topk_5_num_100_update_-1_timestep_0_multi_2_kclosest_1000_artistic"                     --prompts_path "data/long_niche_art_prompts.csv"                     --save_path "evaluation_massive"                     --num_samples 5                     
