# "Erasing imagenette_v1_wo" with ImageNet
CUDA_VISIBLE_DEVICES=0 python train_age.py.py                     --save_freq 200                     --models_path=models                     --prompt "imagenette_v1_wo"                     --seperator ","                     --train_method "xattn"                     --config_path "configs/stable-diffusion/v1-inference.yaml"                     --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt"                     --diffusers_config_path "../Better_Erasing/models/erase/config.json"                     --lr 1e-5                     --gumbel_lr 1e-2                     --gumbel_temp 0.1                     --gumbel_hard 1                     --gumbel_num_centers 100                     --gumbel_update -1                     --gumbel_time_step 0                     --gumbel_multi_steps 2                     --gumbel_k_closest 100                     --vocab "Imagenet"                     --ignore_special_tokens False                     --gumbel_topk 2                     --lamda 1                     --info "gumbel_lr_1e-2_temp_0.1_hard_1_topk_2_num_100_update_-1_timestep_0_multi_2_kclosest_100_vocab_Imagenet"                     
CUDA_VISIBLE_DEVICES=0 python generate_images_ldm.py                     --models_path=models                     --model_name="compvis-adversarial-gumbel-word_imagenette_v1_wo-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_gumbel_lr_1e-2_temp_0.1_hard_1_topk_2_num_100_update_-1_timestep_0_multi_2_kclosest_100_vocab_Imagenet"                     --prompts_path "data/imagenette.csv"                     --save_path "evaluation_massive"                     --num_samples 1                     --from_case 0                     --to_case -1                     
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py                     --topk=10                     --folder_path="evaluation_massive/compvis-adversarial-gumbel-word_imagenette_v1_wo-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_gumbel_lr_1e-2_temp_0.1_hard_1_topk_2_num_100_update_-1_timestep_0_multi_2_kclosest_100_vocab_Imagenet/ldm-imagenette/"                     --prompts_path="data/imagenette.csv"                     --save_path="evaluation_folder/compvis-adversarial-gumbel-word_imagenette_v1_wo-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_gumbel_lr_1e-2_temp_0.1_hard_1_topk_2_num_100_update_-1_timestep_0_multi_2_kclosest_100_vocab_Imagenet-ldm-imagenette.csv"                    


# "Erasing imagenette_v1_wo" with EN3K 
CUDA_VISIBLE_DEVICES=0 python train_age.py.py                     --save_freq 200                     --models_path=models                     --prompt "imagenette_v1_wo"                     --seperator ","                     --train_method "xattn"                     --config_path "configs/stable-diffusion/v1-inference.yaml"                     --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt"                     --diffusers_config_path "../Better_Erasing/models/erase/config.json"                     --lr 1e-5                     --gumbel_lr 1e-2                     --gumbel_temp 0.1                     --gumbel_hard 1                     --gumbel_num_centers 100                     --gumbel_update -1                     --gumbel_time_step 0                     --gumbel_multi_steps 2                     --gumbel_k_closest 100                     --vocab "EN3K"                     --ignore_special_tokens False                     --gumbel_topk 2                     --lamda 1                     --info "gumbel_lr_1e-2_temp_0.1_hard_1_topk_2_num_100_update_-1_timestep_0_multi_2_kclosest_100_vocab_EN3K"                     
CUDA_VISIBLE_DEVICES=0 python generate_images_ldm.py                     --models_path=models                     --model_name="compvis-adversarial-gumbel-word_imagenette_v1_wo-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_gumbel_lr_1e-2_temp_0.1_hard_1_topk_2_num_100_update_-1_timestep_0_multi_2_kclosest_100_vocab_EN3K"                     --prompts_path "data/imagenette.csv"                     --save_path "evaluation_massive"                     --num_samples 1                     --from_case 0                     --to_case -1                     
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py                     --topk=10                     --folder_path="evaluation_massive/compvis-adversarial-gumbel-word_imagenette_v1_wo-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_gumbel_lr_1e-2_temp_0.1_hard_1_topk_2_num_100_update_-1_timestep_0_multi_2_kclosest_100_vocab_EN3K/ldm-imagenette/"                     --prompts_path="data/imagenette.csv"                     --save_path="evaluation_folder/compvis-adversarial-gumbel-word_imagenette_v1_wo-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_gumbel_lr_1e-2_temp_0.1_hard_1_topk_2_num_100_update_-1_timestep_0_multi_2_kclosest_100_vocab_EN3K-ldm-imagenette.csv"                    

# "Erasing imagenette_v1_wo" with CLIP
CUDA_VISIBLE_DEVICES=0 python train_age.py.py                     --save_freq 50                     --models_path=models                     --prompt "imagenette_v1_wo"                     --seperator ","                     --train_method "xattn"                     --config_path "configs/stable-diffusion/v1-inference.yaml"                     --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt"                     --diffusers_config_path "../Better_Erasing/models/erase/config.json"                     --lr 1e-5                     --gumbel_lr 1e-2                     --gumbel_temp 0.1                     --gumbel_hard 1                     --gumbel_num_centers 100                     --gumbel_update -1                     --gumbel_time_step 0                     --gumbel_multi_steps 2                     --gumbel_k_closest 100                     --vocab "CLIP"                     --ignore_special_tokens False                     --gumbel_topk 2                     --lamda 1                     --info "gumbel_lr_1e-2_temp_0.1_hard_1_topk_2_num_100_update_-1_timestep_0_multi_2_kclosest_100_vocab_CLIP"                     
CUDA_VISIBLE_DEVICES=0 python generate_images_ldm.py                     --models_path=models                     --model_name="compvis-adversarial-gumbel-word_imagenette_v1_wo-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_gumbel_lr_1e-2_temp_0.1_hard_1_topk_2_num_100_update_-1_timestep_0_multi_2_kclosest_100_vocab_CLIP"                     --prompts_path "data/imagenette.csv"                     --save_path "evaluation_massive"                     --num_samples 1                     --from_case 0                     --to_case -1     
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py                     --topk=10                     --folder_path="evaluation_massive/compvis-adversarial-gumbel-word_imagenette_v1_wo-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_gumbel_lr_1e-2_temp_0.1_hard_1_topk_2_num_100_update_-1_timestep_0_multi_2_kclosest_100_vocab_CLIP/ldm-imagenette/"                     --prompts_path="data/imagenette.csv"                     --save_path="evaluation_folder/compvis-adversarial-gumbel-word_imagenette_v1_wo-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_gumbel_lr_1e-2_temp_0.1_hard_1_topk_2_num_100_update_-1_timestep_0_multi_2_kclosest_100_vocab_CLIP-ldm-imagenette.csv"                    

# "Erasing imagenette_v1_wo" with keyword 
# CUDA_VISIBLE_DEVICES=0 python train_age.py.py                     --save_freq 50                     --models_path=models                     --prompt "imagenette_v1_wo"                     --seperator ","                     --train_method "xattn"                     --config_path "configs/stable-diffusion/v1-inference.yaml"                     --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt"                     --diffusers_config_path "../Better_Erasing/models/erase/config.json"                     --lr 1e-5                     --gumbel_lr 1e-2                     --gumbel_temp 0.1                     --gumbel_hard 1                     --gumbel_num_centers 100                     --gumbel_update -1                     --gumbel_time_step 0                     --gumbel_multi_steps 2                     --gumbel_k_closest 100                     --vocab "keyword"                     --ignore_special_tokens False                     --gumbel_topk 2                     --lamda 1                     --info "gumbel_lr_1e-2_temp_0.1_hard_1_topk_2_num_100_update_-1_timestep_0_multi_2_kclosest_100_vocab_keyword"                     
CUDA_VISIBLE_DEVICES=0 python generate_images_ldm.py                     --models_path=models                     --model_name="compvis-adversarial-gumbel-word_imagenette_v1_wo-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_gumbel_lr_1e-2_temp_0.1_hard_1_topk_2_num_100_update_-1_timestep_0_multi_2_kclosest_100_vocab_keyword"                     --prompts_path "data/imagenette.csv"                     --save_path "evaluation_massive"                     --num_samples 1                     --from_case 4520                     --to_case -1                     
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py                     --topk=10                     --folder_path="evaluation_massive/compvis-adversarial-gumbel-word_imagenette_v1_wo-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_gumbel_lr_1e-2_temp_0.1_hard_1_topk_2_num_100_update_-1_timestep_0_multi_2_kclosest_100_vocab_keyword/ldm-imagenette/"                     --prompts_path="data/imagenette.csv"                     --save_path="evaluation_folder/compvis-adversarial-gumbel-word_imagenette_v1_wo-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_gumbel_lr_1e-2_temp_0.1_hard_1_topk_2_num_100_update_-1_timestep_0_multi_2_kclosest_100_vocab_keyword-ldm-imagenette.csv"                    

