# Tasks for device 0

# "Erasing EnglishSpringer with target SpringerSpaniel"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "English Springer" --target "Springer Spaniel" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/naive_erase_EnglishSpringer_target_SpringerSpaniel_train.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-naive-word_EnglishSpringer-target_SpringerSpaniel-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee -a "logs/naive_erase_EnglishSpringer_target_SpringerSpaniel_generate.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-naive-word_EnglishSpringer-target_SpringerSpaniel-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-naive-word_EnglishSpringer-target_SpringerSpaniel-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing EnglishSpringer with target ClumberSpaniel"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "English Springer" --target "Clumber Spaniel" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/naive_erase_EnglishSpringer_target_ClumberSpaniel_train.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-naive-word_EnglishSpringer-target_ClumberSpaniel-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee -a "logs/naive_erase_EnglishSpringer_target_ClumberSpaniel_generate.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-naive-word_EnglishSpringer-target_ClumberSpaniel-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-naive-word_EnglishSpringer-target_ClumberSpaniel-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing EnglishSpringer with target Dog"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "English Springer" --target "Dog" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/naive_erase_EnglishSpringer_target_Dog_train.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-naive-word_EnglishSpringer-target_Dog-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee -a "logs/naive_erase_EnglishSpringer_target_Dog_generate.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-naive-word_EnglishSpringer-target_Dog-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-naive-word_EnglishSpringer-target_Dog-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing EnglishSpringer with target GarbageTruck"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "English Springer" --target "Garbage Truck" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/naive_erase_EnglishSpringer_target_GarbageTruck_train.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-naive-word_EnglishSpringer-target_GarbageTruck-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee -a "logs/naive_erase_EnglishSpringer_target_GarbageTruck_generate.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-naive-word_EnglishSpringer-target_GarbageTruck-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-naive-word_EnglishSpringer-target_GarbageTruck-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing FrenchHorn with target BrassHorn"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "French Horn" --target "Brass Horn" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/naive_erase_FrenchHorn_target_BrassHorn_train.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-naive-word_FrenchHorn-target_BrassHorn-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee -a "logs/naive_erase_FrenchHorn_target_BrassHorn_generate.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-naive-word_FrenchHorn-target_BrassHorn-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-naive-word_FrenchHorn-target_BrassHorn-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing FrenchHorn with target Bassoon"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "French Horn" --target "Bassoon" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/naive_erase_FrenchHorn_target_Bassoon_train.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-naive-word_FrenchHorn-target_Bassoon-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee -a "logs/naive_erase_FrenchHorn_target_Bassoon_generate.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-naive-word_FrenchHorn-target_Bassoon-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-naive-word_FrenchHorn-target_Bassoon-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing FrenchHorn with target MusicalInstrumentHorn"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "French Horn" --target "Musical Instrument Horn" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/naive_erase_FrenchHorn_target_MusicalInstrumentHorn_train.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-naive-word_FrenchHorn-target_MusicalInstrumentHorn-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee -a "logs/naive_erase_FrenchHorn_target_MusicalInstrumentHorn_generate.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-naive-word_FrenchHorn-target_MusicalInstrumentHorn-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-naive-word_FrenchHorn-target_MusicalInstrumentHorn-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing FrenchHorn with target Church"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "French Horn" --target "Church" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/naive_erase_FrenchHorn_target_Church_train.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-naive-word_FrenchHorn-target_Church-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee -a "logs/naive_erase_FrenchHorn_target_Church_generate.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-naive-word_FrenchHorn-target_Church-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-naive-word_FrenchHorn-target_Church-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing CassettePlayer with target TapePlayer"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Cassette Player" --target "Tape Player" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/naive_erase_CassettePlayer_target_TapePlayer_train.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-naive-word_CassettePlayer-target_TapePlayer-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee -a "logs/naive_erase_CassettePlayer_target_TapePlayer_generate.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-naive-word_CassettePlayer-target_TapePlayer-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-naive-word_CassettePlayer-target_TapePlayer-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing CassettePlayer with target PolaroidCamera"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Cassette Player" --target "Polaroid Camera" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/naive_erase_CassettePlayer_target_PolaroidCamera_train.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-naive-word_CassettePlayer-target_PolaroidCamera-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee -a "logs/naive_erase_CassettePlayer_target_PolaroidCamera_generate.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-naive-word_CassettePlayer-target_PolaroidCamera-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-naive-word_CassettePlayer-target_PolaroidCamera-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing CassettePlayer with target AudioDevice"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Cassette Player" --target "Audio Device" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/naive_erase_CassettePlayer_target_AudioDevice_train.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-naive-word_CassettePlayer-target_AudioDevice-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee -a "logs/naive_erase_CassettePlayer_target_AudioDevice_generate.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-naive-word_CassettePlayer-target_AudioDevice-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-naive-word_CassettePlayer-target_AudioDevice-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing CassettePlayer with target EnglishSpringer"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Cassette Player" --target "English Springer" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/naive_erase_CassettePlayer_target_EnglishSpringer_train.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-naive-word_CassettePlayer-target_EnglishSpringer-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee -a "logs/naive_erase_CassettePlayer_target_EnglishSpringer_generate.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-naive-word_CassettePlayer-target_EnglishSpringer-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-naive-word_CassettePlayer-target_EnglishSpringer-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# Tasks for device 1

# "Erasing GarbageTruck with target WasteCollectionVehicle"
CUDA_VISIBLE_DEVICES=1 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Garbage Truck" --target "Waste Collection Vehicle" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/naive_erase_GarbageTruck_target_WasteCollectionVehicle_train.log"
CUDA_VISIBLE_DEVICES=1 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-naive-word_GarbageTruck-target_WasteCollectionVehicle-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee -a "logs/naive_erase_GarbageTruck_target_WasteCollectionVehicle_generate.log"
CUDA_VISIBLE_DEVICES=1 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-naive-word_GarbageTruck-target_WasteCollectionVehicle-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-naive-word_GarbageTruck-target_WasteCollectionVehicle-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing GarbageTruck with target MovingVan"
CUDA_VISIBLE_DEVICES=1 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Garbage Truck" --target "Moving Van" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/naive_erase_GarbageTruck_target_MovingVan_train.log"
CUDA_VISIBLE_DEVICES=1 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-naive-word_GarbageTruck-target_MovingVan-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee -a "logs/naive_erase_GarbageTruck_target_MovingVan_generate.log"
CUDA_VISIBLE_DEVICES=1 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-naive-word_GarbageTruck-target_MovingVan-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-naive-word_GarbageTruck-target_MovingVan-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing GarbageTruck with target Truck"
CUDA_VISIBLE_DEVICES=1 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Garbage Truck" --target "Truck" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/naive_erase_GarbageTruck_target_Truck_train.log"
CUDA_VISIBLE_DEVICES=1 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-naive-word_GarbageTruck-target_Truck-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee -a "logs/naive_erase_GarbageTruck_target_Truck_generate.log"
CUDA_VISIBLE_DEVICES=1 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-naive-word_GarbageTruck-target_Truck-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-naive-word_GarbageTruck-target_Truck-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing GarbageTruck with target FrenchHorn"
CUDA_VISIBLE_DEVICES=1 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Garbage Truck" --target "French Horn" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/naive_erase_GarbageTruck_target_FrenchHorn_train.log"
CUDA_VISIBLE_DEVICES=1 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-naive-word_GarbageTruck-target_FrenchHorn-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee -a "logs/naive_erase_GarbageTruck_target_FrenchHorn_generate.log"
CUDA_VISIBLE_DEVICES=1 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-naive-word_GarbageTruck-target_FrenchHorn-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-naive-word_GarbageTruck-target_FrenchHorn-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing Church with target Chapel"
CUDA_VISIBLE_DEVICES=1 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Church" --target "Chapel" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/naive_erase_Church_target_Chapel_train.log"
CUDA_VISIBLE_DEVICES=1 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-naive-word_Church-target_Chapel-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee -a "logs/naive_erase_Church_target_Chapel_generate.log"
CUDA_VISIBLE_DEVICES=1 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-naive-word_Church-target_Chapel-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-naive-word_Church-target_Chapel-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing Church with target Monastery"
CUDA_VISIBLE_DEVICES=1 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Church" --target "Monastery" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/naive_erase_Church_target_Monastery_train.log"
CUDA_VISIBLE_DEVICES=1 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-naive-word_Church-target_Monastery-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee -a "logs/naive_erase_Church_target_Monastery_generate.log"
CUDA_VISIBLE_DEVICES=1 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-naive-word_Church-target_Monastery-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-naive-word_Church-target_Monastery-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing Church with target Building"
CUDA_VISIBLE_DEVICES=1 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Church" --target "Building" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/naive_erase_Church_target_Building_train.log"
CUDA_VISIBLE_DEVICES=1 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-naive-word_Church-target_Building-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee -a "logs/naive_erase_Church_target_Building_generate.log"
CUDA_VISIBLE_DEVICES=1 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-naive-word_Church-target_Building-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-naive-word_Church-target_Building-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing Church with target CassettePlayer"
CUDA_VISIBLE_DEVICES=1 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Church" --target "Cassette Player" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/naive_erase_Church_target_CassettePlayer_train.log"
CUDA_VISIBLE_DEVICES=1 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-naive-word_Church-target_CassettePlayer-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee -a "logs/naive_erase_Church_target_CassettePlayer_generate.log"
CUDA_VISIBLE_DEVICES=1 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-naive-word_Church-target_CassettePlayer-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-naive-word_Church-target_CassettePlayer-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

