# Tasks for device 0

# "Erasing English Springer"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "English Springer" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_0_train_EnglishSpringer.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_EnglishSpringer-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_0_generate_EnglishSpringer.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_EnglishSpringer-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_EnglishSpringer-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing Clumber Spaniel"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Clumber Spaniel" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_1_train_ClumberSpaniel.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_ClumberSpaniel-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_1_generate_ClumberSpaniel.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_ClumberSpaniel-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_ClumberSpaniel-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing English Setter"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "English Setter" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_2_train_EnglishSetter.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_EnglishSetter-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_2_generate_EnglishSetter.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_EnglishSetter-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_EnglishSetter-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing Blenheim Spaniel"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Blenheim Spaniel" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_3_train_BlenheimSpaniel.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_BlenheimSpaniel-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_3_generate_BlenheimSpaniel.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_BlenheimSpaniel-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_BlenheimSpaniel-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing Border Collie"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Border Collie" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_4_train_BorderCollie.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_BorderCollie-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_4_generate_BorderCollie.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_BorderCollie-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_BorderCollie-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing dog"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "dog" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_5_train_dog.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_dog-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_5_generate_dog.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_dog-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_dog-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing Garbage Truck"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Garbage Truck" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_6_train_GarbageTruck.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_GarbageTruck-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_6_generate_GarbageTruck.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_GarbageTruck-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_GarbageTruck-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing Moving Van"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Moving Van" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_7_train_MovingVan.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_MovingVan-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_7_generate_MovingVan.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_MovingVan-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_MovingVan-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing Fire Engine"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Fire Engine" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_8_train_FireEngine.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_FireEngine-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_8_generate_FireEngine.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_FireEngine-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_FireEngine-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing Ambulance"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Ambulance" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_9_train_Ambulance.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_Ambulance-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_9_generate_Ambulance.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_Ambulance-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_Ambulance-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing School Bus"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "School Bus" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_10_train_SchoolBus.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_SchoolBus-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_10_generate_SchoolBus.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_SchoolBus-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_SchoolBus-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing car"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "car" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_11_train_car.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_car-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_11_generate_car.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_car-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_car-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing truck"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "truck" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_12_train_truck.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_truck-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_12_generate_truck.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_truck-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_truck-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing French Horn"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "French Horn" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_13_train_FrenchHorn.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_FrenchHorn-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_13_generate_FrenchHorn.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_FrenchHorn-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_FrenchHorn-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing Bassoon"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Bassoon" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_14_train_Bassoon.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_Bassoon-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_14_generate_Bassoon.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_Bassoon-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_Bassoon-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing Trombone"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Trombone" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_15_train_Trombone.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_Trombone-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_15_generate_Trombone.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_Trombone-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_Trombone-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing Oboe"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Oboe" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_16_train_Oboe.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_Oboe-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_16_generate_Oboe.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_Oboe-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_Oboe-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing Saxophone"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Saxophone" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_17_train_Saxophone.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_Saxophone-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_17_generate_Saxophone.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_Saxophone-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_Saxophone-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing musical instrument"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "musical instrument" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_18_train_musicalinstrument.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_musicalinstrument-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_18_generate_musicalinstrument.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_musicalinstrument-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_musicalinstrument-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing Church"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Church" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_19_train_Church.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_Church-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_19_generate_Church.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_Church-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_Church-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing Monastery"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Monastery" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_20_train_Monastery.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_Monastery-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_20_generate_Monastery.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_Monastery-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_Monastery-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing Bell Cote"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Bell Cote" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_21_train_BellCote.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_BellCote-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_21_generate_BellCote.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_BellCote-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_BellCote-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing Dome"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Dome" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_22_train_Dome.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_Dome-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_22_generate_Dome.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_Dome-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_Dome-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing Library"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Library" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_23_train_Library.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_Library-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_23_generate_Library.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_Library-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_Library-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing building"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "building" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_24_train_building.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_building-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_24_generate_building.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_building-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_building-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing Cassette Player"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Cassette Player" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_25_train_CassettePlayer.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_CassettePlayer-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_25_generate_CassettePlayer.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_CassettePlayer-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_CassettePlayer-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing Polaroid Camera"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Polaroid Camera" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_26_train_PolaroidCamera.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_PolaroidCamera-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_26_generate_PolaroidCamera.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_PolaroidCamera-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_PolaroidCamera-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing Loudspeaker"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Loudspeaker" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_27_train_Loudspeaker.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_Loudspeaker-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_27_generate_Loudspeaker.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_Loudspeaker-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_Loudspeaker-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing Typewriter Keyboard"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Typewriter Keyboard" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_28_train_TypewriterKeyboard.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_TypewriterKeyboard-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_28_generate_TypewriterKeyboard.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_TypewriterKeyboard-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_TypewriterKeyboard-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

# "Erasing Projectoraudio device"
CUDA_VISIBLE_DEVICES=0 python train-naive.py --seperator "," --train_method "xattn" --ckpt_path "../Better_Erasing/models/erase/sd-v1-4-full-ema.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Projectoraudio device" --config_path "configs/stable-diffusion/v1-inference.yaml" --info "none" | tee "logs/target-empty_29_train_Projectoraudiodevice.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/generate-images.py --models_path=models --model_name="compvis-word_Projectoraudiodevice-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none" --prompts_path "data/netfive_500.csv" --save_path "evaluation_netfive_500" --num_samples 1 --from_case 0 --to_case -1 | tee "logs/target-empty_29_generate_Projectoraudiodevice.log"
CUDA_VISIBLE_DEVICES=0 python eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_500/compvis-word_Projectoraudiodevice-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none/netfive_500/" --prompts_path="data/netfive_500.csv" --save_path="evaluation_folder/compvis-word_Projectoraudiodevice-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_none-netfive_500.csv"

