# Tasks for device 0

# "Erasing EnglishSpringer with target ClumberSpaniel"
CUDA_VISIBLE_DEVICES=0 python3 train-esd.py --seperator "," --train_method "xattn" --ckpt_path "checkpoints/v2-1_512-ema-pruned.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "English Springer" --target "Clumber Spaniel" --config_path "configs/stable-diffusion/v2-inference-fp32.yaml" --info "SDv21" | tee "logs/erase_EnglishSpringer_target_ClumberSpaniel_train.log"
CUDA_VISIBLE_DEVICES=0 python3 generate_images_ldm_sdv2.py --config="configs/stable-diffusion/v2-inference.yaml" --ckpt "models/compvis-word_EnglishSpringer-target_ClumberSpaniel-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/compvis-word_EnglishSpringer-target_ClumberSpaniel-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.pt" --prompts_path "data/netfive_100.csv" --H 512 --W 512 --n_samples 1 --outdir "evaluation_netfive_100/compvis-word_EnglishSpringer-target_ClumberSpaniel-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100" | tee -a "logs/erase_EnglishSpringer_target_ClumberSpaniel_generate.log"
CUDA_VISIBLE_DEVICES=0 python3 eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_100/compvis-word_EnglishSpringer-target_ClumberSpaniel-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100/samples/" --prompts_path="data/netfive_100.csv" --save_path="evaluation_folder/compvis-word_EnglishSpringer-target_ClumberSpaniel-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21-netfive_100.csv"


# "Erasing GarbageTruck with target MovingVan"
CUDA_VISIBLE_DEVICES=0 python3 train-esd.py --seperator "," --train_method "xattn" --ckpt_path "checkpoints/v2-1_512-ema-pruned.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Garbage Truck" --target "Moving Van" --config_path "configs/stable-diffusion/v2-inference-fp32.yaml" --info "SDv21" | tee "logs/erase_GarbageTruck_target_MovingVan_train.log"
CUDA_VISIBLE_DEVICES=0 python3 generate_images_ldm_sdv2.py --config="configs/stable-diffusion/v2-inference.yaml" --ckpt "models/compvis-word_GarbageTruck-target_MovingVan-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/compvis-word_GarbageTruck-target_MovingVan-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.pt" --prompts_path "data/netfive_100.csv" --H 512 --W 512 --n_samples 1 --outdir "evaluation_netfive_100/compvis-word_GarbageTruck-target_MovingVan-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100" | tee -a "logs/erase_GarbageTruck_target_MovingVan_generate.log"
CUDA_VISIBLE_DEVICES=0 python3 eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_100/compvis-word_GarbageTruck-target_MovingVan-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100/samples/" --prompts_path="data/netfive_100.csv" --save_path="evaluation_folder/compvis-word_GarbageTruck-target_MovingVan-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21-netfive_100.csv"


# "Erasing FrenchHorn with target Bassoon"
CUDA_VISIBLE_DEVICES=0 python3 train-esd.py --seperator "," --train_method "xattn" --ckpt_path "checkpoints/v2-1_512-ema-pruned.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "French Horn" --target "Bassoon" --config_path "configs/stable-diffusion/v2-inference-fp32.yaml" --info "SDv21" | tee "logs/erase_FrenchHorn_target_Bassoon_train.log"
CUDA_VISIBLE_DEVICES=0 python3 generate_images_ldm_sdv2.py --config="configs/stable-diffusion/v2-inference.yaml" --ckpt "models/compvis-word_FrenchHorn-target_Bassoon-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/compvis-word_FrenchHorn-target_Bassoon-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.pt" --prompts_path "data/netfive_100.csv" --H 512 --W 512 --n_samples 1 --outdir "evaluation_netfive_100/compvis-word_FrenchHorn-target_Bassoon-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100" | tee -a "logs/erase_FrenchHorn_target_Bassoon_generate.log"
CUDA_VISIBLE_DEVICES=0 python3 eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_100/compvis-word_FrenchHorn-target_Bassoon-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100/samples/" --prompts_path="data/netfive_100.csv" --save_path="evaluation_folder/compvis-word_FrenchHorn-target_Bassoon-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21-netfive_100.csv"


# "Erasing Church with target Monastery"
CUDA_VISIBLE_DEVICES=0 python3 train-esd.py --seperator "," --train_method "xattn" --ckpt_path "checkpoints/v2-1_512-ema-pruned.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Church" --target "Monastery" --config_path "configs/stable-diffusion/v2-inference-fp32.yaml" --info "SDv21" | tee "logs/erase_Church_target_Monastery_train.log"
CUDA_VISIBLE_DEVICES=2 python3 generate_images_ldm_sdv2.py --config="configs/stable-diffusion/v2-inference.yaml" --ckpt "models/compvis-word_Church-target_Monastery-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/compvis-word_Church-target_Monastery-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.pt" --prompts_path "data/netfive_100.csv" --H 512 --W 512 --n_samples 1 --outdir "evaluation_netfive_100/compvis-word_Church-target_Monastery-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100" --from_case 1240 | tee -a "logs/erase_Church_target_Monastery_generate.log"
CUDA_VISIBLE_DEVICES=2 python3 eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_100/compvis-word_Church-target_Monastery-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100/samples/" --prompts_path="data/netfive_100.csv" --save_path="evaluation_folder/compvis-word_Church-target_Monastery-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21-netfive_100.csv"


# "Erasing CassettePlayer with target PolaroidCamera"
CUDA_VISIBLE_DEVICES=0 python3 train-esd.py --seperator "," --train_method "xattn" --ckpt_path "checkpoints/v2-1_512-ema-pruned.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Cassette Player" --target "Polaroid Camera" --config_path "configs/stable-diffusion/v2-inference-fp32.yaml" --info "SDv21" | tee "logs/erase_CassettePlayer_target_PolaroidCamera_train.log"
CUDA_VISIBLE_DEVICES=2 python3 generate_images_ldm_sdv2.py --config="configs/stable-diffusion/v2-inference.yaml" --ckpt "models/compvis-word_CassettePlayer-target_PolaroidCamera-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/compvis-word_CassettePlayer-target_PolaroidCamera-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.pt" --prompts_path "data/netfive_100.csv" --H 512 --W 512 --n_samples 1 --outdir "evaluation_netfive_100/compvis-word_CassettePlayer-target_PolaroidCamera-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100" | tee -a "logs/erase_CassettePlayer_target_PolaroidCamera_generate.log"
CUDA_VISIBLE_DEVICES=2 python3 eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_100/compvis-word_CassettePlayer-target_PolaroidCamera-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100/samples/" --prompts_path="data/netfive_100.csv" --save_path="evaluation_folder/compvis-word_CassettePlayer-target_PolaroidCamera-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21-netfive_100.csv"

# Tasks for device 1

# "Erasing EnglishSpringer with target BorderCollie"
CUDA_VISIBLE_DEVICES=1 python3 train-esd.py --seperator "," --train_method "xattn" --ckpt_path "checkpoints/v2-1_512-ema-pruned.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "English Springer" --target "Border Collie" --config_path "configs/stable-diffusion/v2-inference-fp32.yaml" --info "SDv21" | tee "logs/erase_EnglishSpringer_target_BorderCollie_train.log"
CUDA_VISIBLE_DEVICES=1 python3 generate_images_ldm_sdv2.py --config="configs/stable-diffusion/v2-inference.yaml" --ckpt "models/compvis-word_EnglishSpringer-target_BorderCollie-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/compvis-word_EnglishSpringer-target_BorderCollie-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.pt" --prompts_path "data/netfive_100.csv" --H 512 --W 512 --n_samples 1 --outdir "evaluation_netfive_100/compvis-word_EnglishSpringer-target_BorderCollie-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100" | tee -a "logs/erase_EnglishSpringer_target_BorderCollie_generate.log"
CUDA_VISIBLE_DEVICES=1 python3 eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_100/compvis-word_EnglishSpringer-target_BorderCollie-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100/samples/" --prompts_path="data/netfive_100.csv" --save_path="evaluation_folder/compvis-word_EnglishSpringer-target_BorderCollie-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21-netfive_100.csv"


# "Erasing GarbageTruck with target SchoolBus"
CUDA_VISIBLE_DEVICES=1 python3 train-esd.py --seperator "," --train_method "xattn" --ckpt_path "checkpoints/v2-1_512-ema-pruned.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Garbage Truck" --target "School Bus" --config_path "configs/stable-diffusion/v2-inference-fp32.yaml" --info "SDv21" | tee "logs/erase_GarbageTruck_target_SchoolBus_train.log"
CUDA_VISIBLE_DEVICES=1 python3 generate_images_ldm_sdv2.py --config="configs/stable-diffusion/v2-inference.yaml" --ckpt "models/compvis-word_GarbageTruck-target_SchoolBus-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/compvis-word_GarbageTruck-target_SchoolBus-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.pt" --prompts_path "data/netfive_100.csv" --H 512 --W 512 --n_samples 1 --outdir "evaluation_netfive_100/compvis-word_GarbageTruck-target_SchoolBus-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100" | tee -a "logs/erase_GarbageTruck_target_SchoolBus_generate.log"
CUDA_VISIBLE_DEVICES=1 python3 eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_100/compvis-word_GarbageTruck-target_SchoolBus-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100/samples/" --prompts_path="data/netfive_100.csv" --save_path="evaluation_folder/compvis-word_GarbageTruck-target_SchoolBus-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21-netfive_100.csv"


# "Erasing FrenchHorn with target Saxophone"
CUDA_VISIBLE_DEVICES=1 python3 train-esd.py --seperator "," --train_method "xattn" --ckpt_path "checkpoints/v2-1_512-ema-pruned.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "French Horn" --target "Saxophone" --config_path "configs/stable-diffusion/v2-inference-fp32.yaml" --info "SDv21" | tee "logs/erase_FrenchHorn_target_Saxophone_train.log"
CUDA_VISIBLE_DEVICES=1 python3 generate_images_ldm_sdv2.py --config="configs/stable-diffusion/v2-inference.yaml" --ckpt "models/compvis-word_FrenchHorn-target_Saxophone-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/compvis-word_FrenchHorn-target_Saxophone-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.pt" --prompts_path "data/netfive_100.csv" --H 512 --W 512 --n_samples 1 --outdir "evaluation_netfive_100/compvis-word_FrenchHorn-target_Saxophone-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100" | tee -a "logs/erase_FrenchHorn_target_Saxophone_generate.log"
CUDA_VISIBLE_DEVICES=1 python3 eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_100/compvis-word_FrenchHorn-target_Saxophone-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100/samples/" --prompts_path="data/netfive_100.csv" --save_path="evaluation_folder/compvis-word_FrenchHorn-target_Saxophone-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21-netfive_100.csv"


# "Erasing Church with target Library"
CUDA_VISIBLE_DEVICES=1 python3 train-esd.py --seperator "," --train_method "xattn" --ckpt_path "checkpoints/v2-1_512-ema-pruned.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Church" --target "Library" --config_path "configs/stable-diffusion/v2-inference-fp32.yaml" --info "SDv21" | tee "logs/erase_Church_target_Library_train.log"
CUDA_VISIBLE_DEVICES=3 python3 generate_images_ldm_sdv2.py --config="configs/stable-diffusion/v2-inference.yaml" --ckpt "models/compvis-word_Church-target_Library-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/compvis-word_Church-target_Library-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.pt" --prompts_path "data/netfive_100.csv" --H 512 --W 512 --n_samples 1 --outdir "evaluation_netfive_100/compvis-word_Church-target_Library-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100" --from_case 1240 | tee -a "logs/erase_Church_target_Library_generate.log"
CUDA_VISIBLE_DEVICES=3 python3 eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_100/compvis-word_Church-target_Library-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100/samples/" --prompts_path="data/netfive_100.csv" --save_path="evaluation_folder/compvis-word_Church-target_Library-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21-netfive_100.csv"


# "Erasing CassettePlayer with target Projector"
CUDA_VISIBLE_DEVICES=1 python3 train-esd.py --seperator "," --train_method "xattn" --ckpt_path "checkpoints/v2-1_512-ema-pruned.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Cassette Player" --target "Projector" --config_path "configs/stable-diffusion/v2-inference-fp32.yaml" --info "SDv21" | tee "logs/erase_CassettePlayer_target_Projector_train.log"
CUDA_VISIBLE_DEVICES=3 python3 generate_images_ldm_sdv2.py --config="configs/stable-diffusion/v2-inference.yaml" --ckpt "models/compvis-word_CassettePlayer-target_Projector-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/compvis-word_CassettePlayer-target_Projector-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.pt" --prompts_path "data/netfive_100.csv" --H 512 --W 512 --n_samples 1 --outdir "evaluation_netfive_100/compvis-word_CassettePlayer-target_Projector-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100" | tee -a "logs/erase_CassettePlayer_target_Projector_generate.log"
CUDA_VISIBLE_DEVICES=3 python3 eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_100/compvis-word_CassettePlayer-target_Projector-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100/samples/" --prompts_path="data/netfive_100.csv" --save_path="evaluation_folder/compvis-word_CassettePlayer-target_Projector-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21-netfive_100.csv"



