# "Running all jobs on device 1"
CUDA_VISIBLE_DEVICES=1 python3 train-esd.py --seperator "," --train_method "xattn" --ckpt_path "checkpoints/v2-1_512-ema-pruned.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "dog" --config_path "configs/stable-diffusion/v2-inference-fp32.yaml" --info "SDv21" | tee "logs/train_compvis-word_dog-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.log"
CUDA_VISIBLE_DEVICES=1 python3 generate_images_ldm_sdv2.py --config="configs/stable-diffusion/v2-inference.yaml" --ckpt "models/compvis-word_dog-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/compvis-word_dog-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.pt" --prompts_path "../Adversarial-Adaptive/data/netfive_100.csv" --H 512 --W 512 --n_samples 1 --outdir "evaluation_netfive_100/compvis-word_dog-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100" | tee "logs/generate_compvis-word_dog-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.log"
CUDA_VISIBLE_DEVICES=1 python3 eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_100/compvis-word_dog-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100/samples/" --prompts_path="../Adversarial-Adaptive/data/netfive_100.csv" --save_path="evaluation_folder/compvis-word_dog-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21-netfive_100.csv"

CUDA_VISIBLE_DEVICES=1 python3 train-esd.py --seperator "," --train_method "xattn" --ckpt_path "checkpoints/v2-1_512-ema-pruned.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "truck" --config_path "configs/stable-diffusion/v2-inference-fp32.yaml" --info "SDv21" | tee "logs/train_compvis-word_truck-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.log"
CUDA_VISIBLE_DEVICES=1 python3 generate_images_ldm_sdv2.py --config="configs/stable-diffusion/v2-inference.yaml" --ckpt "models/compvis-word_truck-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/compvis-word_truck-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.pt" --prompts_path "../Adversarial-Adaptive/data/netfive_100.csv" --H 512 --W 512 --n_samples 1 --outdir "evaluation_netfive_100/compvis-word_truck-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100" | tee "logs/generate_compvis-word_truck-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.log"
CUDA_VISIBLE_DEVICES=1 python3 eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_100/compvis-word_truck-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100/samples/" --prompts_path="../Adversarial-Adaptive/data/netfive_100.csv" --save_path="evaluation_folder/compvis-word_truck-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21-netfive_100.csv"

CUDA_VISIBLE_DEVICES=1 python3 train-esd.py --seperator "," --train_method "xattn" --ckpt_path "checkpoints/v2-1_512-ema-pruned.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "musical instrument" --config_path "configs/stable-diffusion/v2-inference-fp32.yaml" --info "SDv21" | tee "logs/train_compvis-word_musicalinstrument-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.log"
CUDA_VISIBLE_DEVICES=1 python3 generate_images_ldm_sdv2.py --config="configs/stable-diffusion/v2-inference.yaml" --ckpt "models/compvis-word_musicalinstrument-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/compvis-word_musicalinstrument-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.pt" --prompts_path "../Adversarial-Adaptive/data/netfive_100.csv" --H 512 --W 512 --n_samples 1 --outdir "evaluation_netfive_100/compvis-word_musicalinstrument-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100" | tee "logs/generate_compvis-word_musicalinstrument-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.log"
CUDA_VISIBLE_DEVICES=1 python3 eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_100/compvis-word_musicalinstrument-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100/samples/" --prompts_path="../Adversarial-Adaptive/data/netfive_100.csv" --save_path="evaluation_folder/compvis-word_musicalinstrument-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21-netfive_100.csv"

CUDA_VISIBLE_DEVICES=1 python3 train-esd.py --seperator "," --train_method "xattn" --ckpt_path "checkpoints/v2-1_512-ema-pruned.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "building" --config_path "configs/stable-diffusion/v2-inference-fp32.yaml" --info "SDv21" | tee "logs/train_compvis-word_building-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.log"
CUDA_VISIBLE_DEVICES=1 python3 generate_images_ldm_sdv2.py --config="configs/stable-diffusion/v2-inference.yaml" --ckpt "models/compvis-word_building-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/compvis-word_building-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.pt" --prompts_path "../Adversarial-Adaptive/data/netfive_100.csv" --H 512 --W 512 --n_samples 1 --outdir "evaluation_netfive_100/compvis-word_building-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100" | tee "logs/generate_compvis-word_building-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.log"
CUDA_VISIBLE_DEVICES=1 python3 eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_100/compvis-word_building-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100/samples/" --prompts_path="../Adversarial-Adaptive/data/netfive_100.csv" --save_path="evaluation_folder/compvis-word_building-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21-netfive_100.csv"

CUDA_VISIBLE_DEVICES=1 python3 train-esd.py --seperator "," --train_method "xattn" --ckpt_path "checkpoints/v2-1_512-ema-pruned.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "audio device" --config_path "configs/stable-diffusion/v2-inference-fp32.yaml" --info "SDv21" | tee "logs/train_compvis-word_audiodevice-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.log"
CUDA_VISIBLE_DEVICES=1 python3 generate_images_ldm_sdv2.py --config="configs/stable-diffusion/v2-inference.yaml" --ckpt "models/compvis-word_audiodevice-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/compvis-word_audiodevice-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.pt" --prompts_path "../Adversarial-Adaptive/data/netfive_100.csv" --H 512 --W 512 --n_samples 1 --outdir "evaluation_netfive_100/compvis-word_audiodevice-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100" | tee "logs/generate_compvis-word_audiodevice-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.log"
CUDA_VISIBLE_DEVICES=1 python3 eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_100/compvis-word_audiodevice-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100/samples/" --prompts_path="../Adversarial-Adaptive/data/netfive_100.csv" --save_path="evaluation_folder/compvis-word_audiodevice-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21-netfive_100.csv"

CUDA_VISIBLE_DEVICES=1 python3 train-esd.py --seperator "," --train_method "xattn" --ckpt_path "checkpoints/v2-1_512-ema-pruned.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Van Gogh" --config_path "configs/stable-diffusion/v2-inference-fp32.yaml" --info "SDv21" | tee "logs/train_compvis-word_VanGogh-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.log"
CUDA_VISIBLE_DEVICES=1 python3 generate_images_ldm_sdv2.py --config="configs/stable-diffusion/v2-inference.yaml" --ckpt "models/compvis-word_VanGogh-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/compvis-word_VanGogh-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.pt" --prompts_path "../Adversarial-Adaptive/data/netfive_100.csv" --H 512 --W 512 --n_samples 1 --outdir "evaluation_netfive_100/compvis-word_VanGogh-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100" | tee "logs/generate_compvis-word_VanGogh-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.log"
CUDA_VISIBLE_DEVICES=1 python3 eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_100/compvis-word_VanGogh-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100/samples/" --prompts_path="../Adversarial-Adaptive/data/netfive_100.csv" --save_path="evaluation_folder/compvis-word_VanGogh-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21-netfive_100.csv"

CUDA_VISIBLE_DEVICES=1 python3 train-esd.py --seperator "," --train_method "xattn" --ckpt_path "checkpoints/v2-1_512-ema-pruned.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "Taylor Swift" --config_path "configs/stable-diffusion/v2-inference-fp32.yaml" --info "SDv21" | tee "logs/train_compvis-word_TaylorSwift-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.log"
CUDA_VISIBLE_DEVICES=1 python3 generate_images_ldm_sdv2.py --config="configs/stable-diffusion/v2-inference.yaml" --ckpt "models/compvis-word_TaylorSwift-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/compvis-word_TaylorSwift-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.pt" --prompts_path "../Adversarial-Adaptive/data/netfive_100.csv" --H 512 --W 512 --n_samples 1 --outdir "evaluation_netfive_100/compvis-word_TaylorSwift-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100" | tee "logs/generate_compvis-word_TaylorSwift-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.log"
CUDA_VISIBLE_DEVICES=1 python3 eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_100/compvis-word_TaylorSwift-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100/samples/" --prompts_path="../Adversarial-Adaptive/data/netfive_100.csv" --save_path="evaluation_folder/compvis-word_TaylorSwift-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21-netfive_100.csv"

CUDA_VISIBLE_DEVICES=1 python3 train-esd.py --seperator "," --train_method "xattn" --ckpt_path "checkpoints/v2-1_512-ema-pruned.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "gun" --config_path "configs/stable-diffusion/v2-inference-fp32.yaml" --info "SDv21" | tee "logs/train_compvis-word_gun-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.log"
CUDA_VISIBLE_DEVICES=1 python3 generate_images_ldm_sdv2.py --config="configs/stable-diffusion/v2-inference.yaml" --ckpt "models/compvis-word_gun-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/compvis-word_gun-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.pt" --prompts_path "../Adversarial-Adaptive/data/netfive_100.csv" --H 512 --W 512 --n_samples 1 --outdir "evaluation_netfive_100/compvis-word_gun-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100" | tee "logs/generate_compvis-word_gun-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.log"
CUDA_VISIBLE_DEVICES=1 python3 eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_100/compvis-word_gun-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100/samples/" --prompts_path="../Adversarial-Adaptive/data/netfive_100.csv" --save_path="evaluation_folder/compvis-word_gun-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21-netfive_100.csv"

CUDA_VISIBLE_DEVICES=1 python3 train-esd.py --seperator "," --train_method "xattn" --ckpt_path "checkpoints/v2-1_512-ema-pruned.ckpt" --diffusers_config_path "../Better_Erasing/models/erase/config.json" --prompt "nudity" --config_path "configs/stable-diffusion/v2-inference-fp32.yaml" --info "SDv21" | tee "logs/train_compvis-word_nudity-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.log"
CUDA_VISIBLE_DEVICES=1 python3 generate_images_ldm_sdv2.py --config="configs/stable-diffusion/v2-inference.yaml" --ckpt "models/compvis-word_nudity-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/compvis-word_nudity-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.pt" --prompts_path "../Adversarial-Adaptive/data/netfive_100.csv" --H 512 --W 512 --n_samples 1 --outdir "evaluation_netfive_100/compvis-word_nudity-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100" | tee "logs/generate_compvis-word_nudity-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21.log"
CUDA_VISIBLE_DEVICES=1 python3 eval-scripts/imageclassify.py --topk=10 --folder_path="evaluation_netfive_100/compvis-word_nudity-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21/netfive_100/samples/" --prompts_path="../Adversarial-Adaptive/data/netfive_100.csv" --save_path="evaluation_folder/compvis-word_nudity-target_-method_xattn-sg_3-ng_1-iter_1000-lr_1e-05-info_SDv21-netfive_100.csv"


